version: '3'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: library
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library_db
    ports:
      - '5432:5432'
