version: '3'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/code
    depends_on:
      - db
      - kafka
    environment:
      - KAFKA_HOST=kafka:9092 
      - KAFKA_CLIENT_ID=library-client 

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: library
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library_db
    ports:
      - '5432:5432'

  kafka:
    image: confluentinc/cp-kafka:latest  
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,INSIDE://kafka:9093 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE  
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 1000
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest  
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: "yes" 
    ports:
      - '2181:2181'
