version: '3'
services:
  web:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: library
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library_db
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: teste
    ports:
      - '5050:80'
